name: cinemax
description: A Flutter movie app.

publish_to: 'none'

version: 2.0.0-dev+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  http: ^0.13.4
  intl: ^0.17.0
  url_launcher: ^6.0.18
  flutter_inappwebview: ^5.3.2
  shimmer: ^2.0.0
  readmore: ^2.1.0
  photo_view: ^0.14.0
  font_awesome_flutter: ^10.1.0
  share_plus: ^4.0.7
  share_plus_web: ^3.0.0
  firebase_analytics: ^9.3.3
  firebase_core: ^1.21.1
  mixpanel_flutter: ^2.0.0
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  google_nav_bar: ^5.0.6
  firebase_messaging: ^10.0.2
  provider: ^6.0.3
  permission_handler: ^8.2.6
  flutter_downloader: ^1.8.3+2
  dio: ^4.0.6
  #video_player: ^2.4.7
  web_scraper: ^0.1.4
  #flutter_hls_parser: ^2.0.0
  #pod_player: ^0.1.0
  #flutter_spinkit: ^5.1.0
  #subtitle_wrapper_package: ^2.1.0
  #chewie: ^1.3.5
  #subtitle: ^0.1.0-beta.3
  flutter_svg: ^1.1.5
  flutter_download_manager: ^0.5.4
  open_file_plus: ^3.3.0
  path_provider: ^2.0.11
  dynamic_color: ^1.5.4
  #adaptive_theme: ^3.1.1
  webview_flutter: ^3.0.4
  percent_indicator: ^4.2.2
  sqflite: ^2.2.2
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  retry: ^3.1.0
  device_info_plus: ^8.1.0
  dpad_container: ^2.0.3
  #video_viewer: ^1.2.7
  native_device_orientation: ^1.1.4
  google_fonts: ^4.0.3
  subtitle: ^0.1.0-beta.3
  flutter_spinkit: ^5.1.0
  flutter_screen_wake: ^1.0.2
  orientation: ^1.3.0
  better_player: ^0.0.83
  #video_player: 2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/country_flags/
    - assets/images/profiles/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: PoppinsSB
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
    - family: PoppinsBlack
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
    - family: SocialIcons
      fonts:
        - asset: assets/fonts/SocialIcons.ttf
    - family: IMdb
      fonts:
        - asset: assets/fonts/imdb.ttf
  
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#161716"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#FFFFFF"
    color_dark: "#161716"
